### ISSUE TITLE
1GHz crosstalk

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Urukul#68] opened 2022-05-25 07:21 UTC
Reported by Andrew Van Horn at Duke:
"A few months ago, we observed a 1GHz crosstalk on all four output channels of the Urukul 9910 v1.5 and 9912 v1.3 when a 1GHz external clock was connected. This crosstalk occurs independent of the clock source and clock reference connection (SMA or MMCX).

I have attached four scope captures which show the presence of this crosstalk on the Urukul 9910 v1.5 and 9912 v1.3 when using the internal clock reference. The crosstalk is also present when using the 1GHz as the reference. 

We observed the 1GHz reference resulted in lower overall phase noise as expected, so in our systems we plan to use the 1GHz clock reference with a 400MHz LPF on the output of the Urukul to mitigate the effects of this crosstalk. " 

Urukul-9912_v1 5 100MHz Output Int Clock, 1GHz clock disconnected
![Urukul-9912_v1 5 100MHz Output Int Clock, 1GHz clock disconnected](https://user-images.githubusercontent.com/720864/170204094-f90619a5-6c10-4563-94f9-371f32296210.png)

Urukul-9912_v1 5 100MHz Output Int Clock, 1GHz clock connected
![Urukul-9912_v1 5 100MHz Output Int Clock, 1GHz clock connected](https://user-images.githubusercontent.com/720864/170204106-383f23cf-0898-4ba4-ad88-33d147f7748e.png)

Urukul-9910_v1 3 100MHz Output Int Clock, 1GHz clock disconnected
![Urukul-9910_v1 3 100MHz Output Int Clock, 1GHz clock disconnected](https://user-images.githubusercontent.com/720864/170204107-be9f9635-d1f9-416a-9de4-646c80a35b76.png)

Urukul-9910_v1 3 100MHz Output Int Clock, 1GHz clock connected
![Urukul-9910_v1 3 100MHz Output Int Clock, 1GHz clock connected](https://user-images.githubusercontent.com/720864/170204109-ae572948-b2eb-4647-9964-216404d33871.png)

**Comment by sbourdeauducq** [comment] 2022-05-25 07:23
Urukul_v1 5_9910 400MHz_Output With_Filter
![Urukul_v1 5_9910 400MHz_Output With_Filter](https://user-images.githubusercontent.com/720864/170204372-4b16b448-d1b5-4a78-8981-20c5a82a942c.png)


Urukul_v1 5_9910 400MHz_Output No_Filter
![Urukul_v1 5_9910 400MHz_Output No_Filter](https://user-images.githubusercontent.com/720864/170204378-af6d7e81-8b65-4c37-a7d9-2aa84c8ad225.png)


Urukul_v1 5_9910 200MHz_Output With_Filter
![Urukul_v1 5_9910 200MHz_Output With_Filter](https://user-images.githubusercontent.com/720864/170204383-b5d580a5-4b53-4b76-9b9b-6d06d11b0f54.png)


Urukul_v1 5_9910 200MHz_Output No_Filter
![Urukul_v1 5_9910 200MHz_Output No_Filter](https://user-images.githubusercontent.com/720864/170204388-3d999f08-2723-49da-a3ac-61cb0c642889.png)


Urukul_v1 5_9910 100MHz_Output With_Filter
![Urukul_v1 5_9910 100MHz_Output With_Filter](https://user-images.githubusercontent.com/720864/170204394-b6b34771-2b96-4735-82f8-b2bb8fa3affc.png)


Urukul_v1 5_9910 100MHz_Output No_Filter
![Urukul_v1 5_9910 100MHz_Output No_Filter](https://user-images.githubusercontent.com/720864/170204396-87bcf652-75b1-4aae-aadd-9353e559bc12.png)

**Comment by jordens** [comment] 2022-05-25 07:35
Check whether the clock in sma connector and the RF out sma connectors are well clear of the panel everywhere. Also their shields. That's where it typically couples.

**Comment by sbourdeauducq** [comment] 2022-06-01 08:46
"I am quite confident that is not the major source of the issue we are seeing. 

First, the cables were kept as far apart from each other and from the front panel as the geometry of the front panel would allow. 
Second, by configuring the Urukul to use the internal clock source and monitoring the output with a spectrum analyzer, the 1GHz noise only appears when the 1GHz clock is connected to the clock SMA. While I am screwing in the 1GHz SMA, the noise abruptly appears when the signal pin makes contact. "

**Comment by jordens** [comment] 2022-06-01 09:35
The panel and the connectors in that panel. Nothing to do with the cables. It's a manufacturing problem. Has been pointed out numerous times.
Feels awkward to help in this way.

**Comment by andrewvh4** [comment] 2022-06-01 14:22
@jordens Is this manufacturing problem fixed in the next revision of the Urukul? And is there any way to modify current revisions to prevent this noise?

**Comment by jordens** [comment] 2022-06-02 18:10
Afaik no. But I don't know what the next revision is.

See the advice in my initial comment above.

If you don't find it here or on phaser in the meantime I'll try searching it for you next week.

**Comment by andrewvh4** [comment] 2022-06-07 15:46
I modified the Urukul by removing the front panel altogether to eliminate any coupling through the front panel. This eliminated the 1GHz crosstalk.

Internal 125MHz clock, 200MHz output, no front panel
![Screen_0001](https://user-images.githubusercontent.com/31864022/172423938-eda5c4f1-b0fe-4a17-b177-a0201ef26f01.png)


External 1GHz clock, 200MHz output, no front panel
![Screen_0002](https://user-images.githubusercontent.com/31864022/172423893-0fbc1bad-7b4a-418b-8376-4e6199f7884b.png)

**Comment by gkasprow** [comment] 2022-09-17 19:20
Do you mean electrical connection of the SMAs and the panel? We use 3D printed distances to make sure isolation is there.

**Comment by gkasprow** [comment] 2023-05-23 21:01
We confirmed the results. The issue is caused by impedance of optional AC-coupling (isolation) RCs. After we shorted SMA connector to nearby GND with thick wire, the crosstal got reduced by a few dB
In the next revision I will short SMA to GND using 4 thick traces. AC-coupling would require cutting the trace.

**Comment by gkasprow** [comment] 2023-06-21 21:18
fixed in v1.5.5

**Comment by marmeladapk** [comment] 2023-06-23 15:35
@gkasprow Isolation of SMAs also requires removal of resistors on top layer. I think that description on bottom overlay should reflect this.

**Comment by gkasprow** [comment] 2023-06-23 19:29
done

**Closed** 2023-09-07 12:17 UTC
